spring:
  application:
    name: eureka

server:
  port: 1291

eureka:
  server:
    eviction-interval-timer-in-ms: 60000
    enable-self-preservation: true
    renewal-percent-threshold: 0.85
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/